[package]
name = "dsh"
version = "0.0.1"
edition = "2021"

[dependencies]
bytesize = {version = "1.3.0", features = ["serde"]}
chrono = "0.4.39"
clap = { version = "4.5.24", features = ["derive"] }
fs_extra = "1.3.0"
rayon = "1.10.0"
sha2 = "0.10.8"
walkdir = "2.5.0"
